# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9608cc896b00d70d772e8a691adc34c595700ed89036c07d3121143361e17b0877e4b74b3e9cbbbcad44ad74144075f05f525de16b10d62415a8cdd48d4e4182

test:
  secret_key_base: 1b685959a523ae0b06b2f4ff6092b2f578173ea4bac6ca8aa41e4047c596c1ab1b393268e487e915ced9e6bc0066e7fbfe810aceb494c29a6dc025992fdecbab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
